#    __ ___ __  __
#   / //_(_) /_/ /___ __
#  / ,< / / __/ __/ // /
# /_/|_/_/\__/\__/\_, /
#                /___/

include "dank-tabs.conf"
include "dank-theme.conf"

include "/usr/share/gabos/gdots/system/kitty/ittyk.conf"

# Your Configuration goes here
