cursor #f1dfda
cursor_text_color #d8c2bb

foreground            #f1dfda
background            #1a110f
selection_foreground  #442a21
selection_background  #e7bdb1
url_color             #ffb59d

color0   #1a110f
color1   #ff7672
color2   #98ff7f
color3   #ffe572
color4   #f29d82
color5   #763722
color6   #ffb59d
color7   #fff3ef
color8   #a59c99
color9   #ffa29f
color10  #b7ffa5
color11  #ffeea5
color12  #ffc0ab
color13  #ffcbba
color14  #ffddd2
color15  #fffaf8
