
name: Build ISO

on:
  workflow_dispatch:

jobs:

    build-iso:
        name: Build ISO for 'gabos'
        uses: ./.github/workflows/build-iso-reusable.yml
        with:
            image_name: gabos
            installer_dir: ./installer

    build-iso-nvidia:
        name: Build ISO for 'gabos-nvidia'
        uses: ./.github/workflows/build-iso-reusable.yml
        with:
            image_name: gabos-nvidia
            installer_dir: ./installer

