# run with --cap-add sys_admin --security-opt label=disable --squash

FROM localhost/image-template:latest

# Salva il tag originale
COPY base-image.oci.tar /tmp/base-image.oci.tar

COPY ./src /src
RUN --mount=type=cache,target=/var/tmp/libdnf5,id=libdnf5 /src/build.sh
RUN rm -fr /src
